version: "3.7"
services:
  contarapida:
    image: mkadev/contarapida:latest
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:${DB_PASSWORD}@postgres:5432/dashboard_personal
      - REDIS_URL=redis://redis:6379
      - NEXTAUTH_URL=https://dashboard.lojapersonalprime.com/
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
    command: npm start
    depends_on:
      - postgres
      - redis
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1G
      labels:
        - traefik.enable=true
        - traefik.http.routers.dashboard_personal.rule=Host(`dashboard.lojapersonalprime.com`)
        - traefik.http.routers.dashboard_personal.entrypoints=websecure
        - traefik.http.routers.dashboard_personal.tls.certresolver=letsencryptresolver
        - traefik.http.services.dashboard_personal.loadbalancer.server.port=3000
        - traefik.http.services.dashboard_personal.loadbalancer.passHostHeader=true
        - traefik.http.routers.dashboard_personal.service=dashboard_personal
    networks:
      - AcceleraNet

  postgres:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=postgres
      - POSTGRES_DB=dashboard_personal
    deploy:
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
    networks:
      - AcceleraNet

  redis:
    image: redis:7
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    deploy:
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.3"
          memory: 256M
    networks:
      - AcceleraNet

  backup:
    image: prodrigestivill/postgres-backup-local
    volumes:
      - postgres_backup:/backups
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=dashboard_personal
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - SCHEDULE=@daily
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
    deploy:
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.1"
          memory: 128M
    networks:
      - AcceleraNet

volumes:
  postgres_data:
  redis_data:
  postgres_backup:

networks:
  AcceleraNet:
    external: true
    name: AcceleraNet 