# Configuração Docker Stack para ContaRapida (Modo Swarm)
# Otimizado para implantação com 'docker stack deploy'

version: '3.8'

services:
  # Aplicação principal ContaRapida
  app:
    image: mkadev/dashboard_personalprime:latest
    depends_on:
      - postgres
      - redis
    networks:
      - AcceleraNet
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - NEXTAUTH_URL=${NEXTAUTH_URL:-https://${DOMAIN}}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-suachavesecretaforte}
      - DOMAIN=${DOMAIN:-contarapida.example.com}
      - RESEND_API_KEY=${RESEND_API_KEY:-re_dummy_key}
      - GROQ_API_KEY=${GROQ_API_KEY:-gsk_dummy_key}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-sk_dummy_key}
      - GESTAO_CLICK_ACCESS_TOKEN=${GESTAO_CLICK_ACCESS_TOKEN:-dummy_token}
      - GESTAO_CLICK_SECRET_ACCESS_TOKEN=${GESTAO_CLICK_SECRET_ACCESS_TOKEN:-dummy_secret}
    volumes:
      - app-logs:/app/logs
      - app-uploads:/app/public/uploads
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.contarapida.rule=Host(`${DOMAIN:-localhost}`)"
        - "traefik.http.routers.contarapida.entrypoints=websecure"
        - "traefik.http.routers.contarapida.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.contarapida.loadbalancer.server.port=3000"
        - "traefik.http.services.contarapida.loadbalancer.passHostHeader=true"
        - "traefik.docker.network=AcceleraNet"

  # PostgreSQL
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-contarapida}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - AcceleraNet
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.3'
          memory: 256M

  # Redis
  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - AcceleraNet
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.2'
          memory: 128M

networks:
  AcceleraNet:
    external: true

volumes:
  postgres-data:
  redis-data:
  app-logs:
  app-uploads: 