# Configuração Docker Stack para ContaRapida (Modo Swarm)
# Otimizado para implantação com 'docker stack deploy' ou via Portainer
# Versão autônoma - não requer scripts externos

version: '3.8'

services:
  # Aplicação principal ContaRapida
  dashboard_personalprime:
    image: mkadev/dashboard_personalprime:latest
    working_dir: /app
    # Script com logging detalhado, migração do banco de dados e tolerância a falhas
    command: ["/bin/sh", "-c", "echo '=== Iniciando ContaRapida ==='; echo 'Aguardando serviços de suporte...'; sleep 20; echo 'Verificando PostgreSQL...'; if nc -z -v postgres 5432; then echo 'PostgreSQL disponível, executando migrações...'; npx prisma db push --accept-data-loss && echo 'Migrações concluídas com sucesso!'; else echo 'ALERTA: PostgreSQL não responde, pulando migrações!'; fi; echo 'Preparando o ambiente standalone...'; if [ -d '.next/standalone/.next/static' ]; then echo 'Arquivos estáticos já preparados'; else echo 'Copiando arquivos estáticos para standalone...'; mkdir -p .next/standalone/.next; cp -r .next/static .next/standalone/.next/; echo 'Copiando pasta public...'; cp -r public .next/standalone/; fi; echo 'Iniciando aplicação no modo standalone...'; cd /app/.next/standalone && NODE_ENV=production HOSTNAME=0.0.0.0 PORT=3000 node server.js"]
    environment:
      # Configurações essenciais da aplicação
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - NEXT_SHARP_PATH=/app/node_modules/sharp
      - NEXT_PUBLIC_ASSET_PREFIX=https://dashboard.lojapersonalprime.com
      - NEXT_ASSET_PREFIX=https://dashboard.lojapersonalprime.com
      # Conexões de banco de dados e cache
      - DATABASE_URL=postgresql://postgres:aff05699b9de3a6ea2596c4971059bd8@10.0.1.12:5432/dashboard_personalprime?schema=public&connection_limit=5&pool_timeout=10
      - REDIS_URL=redis://redis:6379
      
      # Autenticação e domínio
      - NEXTAUTH_URL=https://dashboard.lojapersonalprime.com
      - NEXTAUTH_SECRET=fb37ccdec4e8586dedf69119941f5389929687ca7860ec2bb437e8797ded3f58
      - DOMAIN=localhost
      - NEXTAUTH_DEBUG=true
      
      # Configuração do ERP Gestão Click (desativada para teste)
      - AUTO_IMPORT_ENABLED=false
      - DEMO_MODE=true
      
      # Configuração de Email (simplificada para teste)
      - EMAIL_FROM=noreply@example.com
      - NEXT_PUBLIC_APP_URL=dashboard.lojapersonalprime.com
      
      # Configuração de Metadata para Next.js
      - NEXT_PUBLIC_METADATA_BASE_URL=https://dashboard.lojapersonalprime.com
    volumes:
      - app-uploads:/app/public/uploads
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
        max_attempts: 5
        delay: 10s
      resources:
        limits:
          cpus: '0.5'
          memory: 384M
        reservations:
          cpus: '0.1'
          memory: 128M
      labels:
        - traefik.enable=true
        - traefik.http.routers.dashboard_personalprime.rule=Host(`dashboard.lojapersonalprime.com`)
        - traefik.http.routers.dashboard_personalprime.entrypoints=websecure
        - traefik.http.routers.dashboard_personalprime.tls.certresolver=letsencryptresolver
        - traefik.http.services.dashboard_personalprime.loadbalancer.server.port=3000
        - traefik.http.services.dashboard_personalprime.loadbalancer.passHostHeader=true
        - traefik.docker.network=AcceleraNet
        - traefik.http.routers.dashboard_personalprime.service=dashboard_personalprime
    networks:
      - AcceleraNet
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/ || exit 0"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
      
  # Banco de dados PostgreSQL local para desenvolvimento
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: dashboard_personalprime
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
    networks:
      - AcceleraNet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  # Adicionar serviço Redis para cache
  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
    networks:
      - AcceleraNet

networks:
  AcceleraNet:
    external: true
    name: AcceleraNet
    
volumes:
  app-uploads:
    driver: local
  postgres-data:
    driver: local
  redis-data:
    driver: local