# Configuração Docker Stack para ContaRapida (Modo Swarm)
# Otimizado para implantação com 'docker stack deploy' ou via Portainer
# Versão autônoma - não requer scripts externos

version: '3.8'

services:
  # Aplicação principal ContaRapida
  dashboard_personalprime:
    image: mkadev/dashboard_personalprime:latest
    working_dir: /app
    # Script com logging detalhado, migração do banco de dados e tolerância a falhas
    command: ["/bin/sh", "-c", "echo '=== Iniciando ContaRapida ==='; echo 'Aguardando serviços de suporte...'; sleep 20; echo 'Verificando PostgreSQL...'; if nc -z -v postgres 5432; then echo 'PostgreSQL disponível, executando migrações...'; npx prisma db push --accept-data-loss && echo 'Migrações concluídas com sucesso!'; else echo 'ALERTA: PostgreSQL não responde, pulando migrações!'; fi; echo 'Iniciando aplicação com servidor customizado...'; NODE_ENV=production HOSTNAME=0.0.0.0 PORT=3000 node server.mjs"]
    environment:
      # Configurações essenciais da aplicação
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - NEXT_SHARP_PATH=/app/node_modules/sharp
      - NEXT_PUBLIC_ASSET_PREFIX=https://dashboard.lojapersonalprime.com
      - NEXT_ASSET_PREFIX=https://dashboard.lojapersonalprime.com
      # Conexões de banco de dados e cache
      - DATABASE_URL=postgresql://postgres:aff05699b9de3a6ea2596c4971059bd8@10.0.1.12:5432/dashboard_personalprime?schema=public&connection_limit=5&pool_timeout=10
      - REDIS_URL=redis://redis:6379

      # Configuração de Email
      - RESEND_API_KEY=re_CuMtc78g_2ckFBFpwMonohLh3Su4XXCnt 
      - EMAIL_SERVER_HOST=smtp.resend.com
      - EMAIL_SERVER_PORT=587
      - EMAIL_SERVER_USER=apikey
      - EMAIL_SERVER_PASSWORD=re_CuMtc78g_2ckFBFpwMonohLh3Su4XXCnt
      - EMAIL_FROM=noreply@acceleracrm.com.br
      # Autenticação e domínio
      - NEXTAUTH_URL=https://dashboard.lojapersonalprime.com
      - NEXTAUTH_SECRET=af088b5bec7db27c5cefe494d4d7bf63183d8d333f21a66e960712336e80d4ca
      - DOMAIN=localhost
      - NEXTAUTH_DEBUG=true

      # Configuração do ERP Gestão Click
      - GESTAO_CLICK_API_URL=https://api.beteltecnologia.com
      - GESTAO_CLICK_ACCESS_TOKEN=35f6a8f4b1f80e1a0c2bb0c85fb6f071ba92e82b
      - GESTAO_CLICK_SECRET_ACCESS_TOKEN=823e5135fab01a057328fbd0a8a99f17aa38933d

      # Configuração do ERP Gestão Click (desativada para teste)
      - AUTO_IMPORT_ENABLED=true
      - DEMO_MODE=false
      
      # Configuração de Email (simplificada para teste)
      - EMAIL_FROM=noreply@example.com
      - NEXT_PUBLIC_APP_URL=https://dashboard.lojapersonalprime.com
      
      # Configuração de Metadata para Next.js
      - NEXT_PUBLIC_METADATA_BASE_URL=https://dashboard.lojapersonalprime.com
    volumes:
      - app-uploads:/app/public/uploads
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
        max_attempts: 5
        delay: 10s
      resources:
        limits:
          cpus: '0.5'
          memory: 384M
        reservations:
          cpus: '0.1'
          memory: 128M
      labels:
        - traefik.enable=true
        - traefik.http.routers.dashboard_personalprime.rule=Host(`dashboard.lojapersonalprime.com`)
        - traefik.http.routers.dashboard_personalprime.entrypoints=websecure
        - traefik.http.routers.dashboard_personalprime.tls.certresolver=letsencryptresolver
        - traefik.http.services.dashboard_personalprime.loadbalancer.server.port=3000
        - traefik.http.services.dashboard_personalprime.loadbalancer.passHostHeader=true
        - traefik.docker.network=AcceleraNet
        - traefik.http.routers.dashboard_personalprime.service=dashboard_personalprime
        - traefik.http.middlewares.websocket.headers.customRequestHeaders.Origin=https://dashboard.lojapersonalprime.com
        - traefik.http.routers.dashboard_personalprime.middlewares=websocket

    networks:
      - AcceleraNet
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider https://dashboard.lojapersonalprime.com || exit 0"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
      
  # Banco de dados PostgreSQL local para desenvolvimento
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: dashboard_personalprime
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
    networks:
      - AcceleraNet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  # Adicionar serviço Redis para cache
  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
    networks:
      - AcceleraNet

networks:
  AcceleraNet:
    external: true
    name: AcceleraNet
    
volumes:
  app-uploads:
    driver: local
  postgres-data:
    driver: local
  redis-data:
    driver: local