"use client";

import { 
  LayoutDashboard, 
  Receipt, 
  Wallet, 
  Target, 
  PiggyBank,
  LineChart, 
  FileSpreadsheet,
  DownloadCloud,
  BrainCircuit,
  School,
  Users,
  BarChart,
  Settings,
  Lock,
  Star,
  Sparkles,
  CreditCard,
  BarChart4,
  PieChart,
  HelpCircle,
  BarChart2,
  FileText,
  Store,
  ShoppingBag,
  MessageCircle,
  TrendingUp,
  Trophy,
  Goal,
  ChartPie,
  MessageSquare,
  BarChart as BarChartIcon,
  UserCircle
} from "lucide-react";
import { MenuSection, SubscriptionPlan } from "./types";

// Definição das seções do menu
export const MENU_SECTIONS: MenuSection[] = [
  {
    title: "Visão Geral",
    items: [
      {
        label: "Dashboard",
        href: "/painel",
        icon: LayoutDashboard,
        plan: SubscriptionPlan.FREE,
        description: "Visão geral das suas finanças",
      },
      {
        label: "Transações",
        href: "/transactions",
        icon: Receipt,
        plan: SubscriptionPlan.FREE,
        description: "Gerenciar receitas e despesas",
        limits: {
          [SubscriptionPlan.FREE]: "Até 50 transações/mês",
          [SubscriptionPlan.BASIC]: "Até 500 transações/mês",
          [SubscriptionPlan.PREMIUM]: "Transações ilimitadas",
        },
      },
      {
        label: "Carteiras",
        href: "/wallets",
        icon: Wallet,
        plan: SubscriptionPlan.FREE,
        description: "Gerenciar suas contas e carteiras",
        limits: {
          [SubscriptionPlan.FREE]: "Até 2 carteiras",
          [SubscriptionPlan.BASIC]: "Até 5 carteiras",
          [SubscriptionPlan.PREMIUM]: "Carteiras ilimitadas",
        },
      },
    ],
  },
  {
    title: "Análises",
    items: [
      {
        label: "Relatórios",
        href: "/reports",
        icon: BarChart4,
        plan: SubscriptionPlan.FREE,
        description: "Relatórios financeiros detalhados",
      },
      {
        label: "Categorias",
        href: "/categories",
        icon: PieChart,
        plan: SubscriptionPlan.FREE,
        description: "Análise de gastos por categoria",
      },
      {
        label: "Análise de IA",
        href: "/ai-insights",
        icon: BrainCircuit,
        plan: SubscriptionPlan.PREMIUM,
        description: "Insights gerados por IA",
        premiumContent: true,
      },
    ],
  },
  {
    title: "Dashboards Comerciais",
    items: [
      {
        label: "Vendas",
        href: "/dashboard/vendas",
        icon: ChartPie,
        plan: SubscriptionPlan.FREE,
        description: "Dados de vendas e faturamento",
      },
      {
        label: "Vendedores",
        href: "/dashboard/vendedores",
        icon: Users,
        plan: SubscriptionPlan.FREE,
        description: "Gerenciamento de fotos e dados dos vendedores",
      },
      {
        label: "Consultores",
        href: "/dashboard/consultores",
        icon: UserCircle,
        plan: SubscriptionPlan.FREE,
        description: "Performance e métricas dos consultores",
      },
      {
        label: "Atendimentos",
        href: "/dashboard/atendimentos",
        icon: MessageSquare,
        plan: SubscriptionPlan.FREE,
        description: "Métricas de atendimento e CRM",
      },
      {
        label: "Conversão",
        href: "/dashboard/conversao",
        icon: BarChartIcon,
        plan: SubscriptionPlan.FREE,
        description: "Taxas de conversão e follow-up",
      },
      {
        label: "Metas",
        href: "/dashboard/metas",
        icon: Target,
        plan: SubscriptionPlan.FREE,
        description: "Acompanhamento de metas comerciais",
      },
      {
        label: "Performance",
        href: "/dashboard/performance",
        icon: TrendingUp,
        plan: SubscriptionPlan.FREE,
        description: "Ranking e bonificação da equipe",
      },
    ],
  },
  {
    title: "Ferramentas",
    items: [
      {
        label: "Metas",
        href: "/goals",
        icon: Target,
        plan: SubscriptionPlan.FREE,
        description: "Definir e acompanhar metas financeiras",
      },
      {
        label: "Orçamentos",
        href: "/budgets",
        icon: PiggyBank,
        plan: SubscriptionPlan.FREE,
        description: "Gerenciar orçamentos e controlar gastos",
      },
      {
        label: "Fluxo de Caixa",
        href: "/cash-flow",
        icon: BarChart2,
        plan: SubscriptionPlan.FREE,
        description: "Visualizar e gerenciar fluxo de caixa futuro",
      },
      {
        label: "Gestão Click",
        href: "/gestao-click",
        icon: Store,
        plan: SubscriptionPlan.FREE,
        description: "Integração com ERP Gestão Click",
      },
      {
        label: "Reconciliação",
        href: "/reconcile-wallets",
        icon: Receipt,
        plan: SubscriptionPlan.FREE,
        description: "Corrigir saldos de carteiras",
      },
      {
        label: "Planejamento",
        href: "/budget",
        icon: BarChart,
        plan: SubscriptionPlan.BASIC,
        description: "Orçamentos mensais e anuais",
      },
      {
        label: "Exportar Dados",
        href: "/export",
        icon: FileText,
        plan: SubscriptionPlan.PREMIUM,
        description: "Exportar relatórios e dados",
        premiumContent: true,
      },
      {
        label: "Integrações",
        href: "/integrations",
        icon: CreditCard,
        plan: SubscriptionPlan.PREMIUM,
        description: "Conectar a bancos e serviços",
        premiumContent: true,
      },
    ],
  },
  {
    title: "Configurações",
    items: [
      {
        label: "Preferências",
        href: "/settings",
        icon: Settings,
        plan: SubscriptionPlan.FREE,
        description: "Personalizar sua experiência",
      },
      {
        label: "Planos",
        href: "/subscription",
        icon: Star,
        plan: SubscriptionPlan.FREE,
        description: "Gerenciar sua assinatura",
      },
      {
        label: "Ajuda",
        href: "/help",
        icon: HelpCircle,
        plan: SubscriptionPlan.FREE,
        description: "Suporte e documentação",
      },
    ],
  }
]; 